name: flutter_news_app_clean_architecture
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  auto_route: ^7.7.1
  card_swiper: ^3.0.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  floor: ^1.4.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.19.0
  get_it: ^7.6.0
  google_fonts: ^5.1.0
  retrofit: ^4.0.1

dev_dependencies:
  auto_route_generator: ^7.2.0
  build_runner: ^2.1.2
  floor_generator: ^1.4.2

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  retrofit_generator: ^7.0.8

flutter:
  uses-material-design: true
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: asset/fonts/Roboto_Bold.ttf
  #       - asset: asset/fonts/Roboto_Medium.ttf
  #       - asset: asset/fonts/Roboto_Regular.ttf
